spring.application.name=learnSpringSecurity

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/learn_security_db
spring.datasource.username=postgres
spring.datasource.password=Deep@nsh.98
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secretKey="Hello I am as secret key.Use me to get enter in auth login"
